In [1]:
import numpy as np

In [2]:
#create one dimension matrix
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
# the dtype function shows the data type in the array
a.dtype

dtype('int64')

In [5]:
# the ndim function return the Number of dimensions
a.ndim

1

In [6]:
# the shape function Return the attributes of the array
a.shape

(3,)

In [7]:
#the size function return the number of items
a.size

3

In [8]:
# the Location of the data in the memory
a.data

In [9]:
#Create two dimension and three dimension Matrix
b = np.array([
    [1,2,3],
    [3,4,5]
])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [10]:
print('type:',b.dtype)
print('number of dimensions:',b.ndim)
print('shape:',b.shape)
print('size:',b.size)

type: int64
number of dimensions: 2
shape: (2, 3)
size: 6


In [11]:
c = np.array([
    [
      [1,2],
      [3,4]
    ],
    [
       [5,6],
       [7,8]
    ]
])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
print('type:',c.dtype)
print('number of dimensions:',c.ndim)
print('shape:',c.shape)
print('size:',c.size)

type: int64
number of dimensions: 3
shape: (2, 2, 2)
size: 8


In [13]:
#data types
x = np.array([2.6,4.7])
x.dtype

dtype('float64')

In [14]:
x = np.array(['ali','nora'])
x.dtype

dtype('<U4')

In [15]:
x = np.array([True,False])
x.dtype

dtype('bool')

In [16]:
#the astype function convert the type of the data
x = np.array(['5','4'])
x.astype(int)

array([5, 4])

In [17]:
#the zeros and ones functions
np.zeros((4,3))#(row,column)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,6))#(row,column)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
# the arange function return an array with a range
np.arange(1,10)#(start,end)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,10,2)#(start,end,Gap)

array([1, 3, 5, 7, 9])

In [21]:
np.arange(1,10,0.5)#(start,end,Gap)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [22]:
#the linspace function return array with a range
np.linspace(1,10,5)#(start,end,number of items)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
# the random function return an array with random numbers
np.random.random((2,3))#(row,column)

array([[0.08797039, 0.41876562, 0.30126631],
       [0.39472016, 0.12624536, 0.3651755 ]])

In [24]:
# the rand function return an array with random numbers between 0 and 1
np.random.rand(3,2)#(row,column)

array([[0.45074811, 0.98035623],
       [0.19277852, 0.67770123],
       [0.64632492, 0.89692788]])

In [25]:
# the randint Function return a  Random number with a range
np.random.randint(1,10)#(start,end)

9

In [26]:
np.random.randint(1,10,size=10)#(start,end,size)

array([9, 9, 2, 2, 8, 7, 8, 9, 6, 9])

In [27]:
np.random.randint(1,10,size=(2,2))#(start,end,size)

array([[6, 5],
       [3, 8]])

In [28]:
#the full function return an array full with an item or items
np.full((2,3),10)#(shape,item)

array([[10, 10, 10],
       [10, 10, 10]])

In [29]:
np.full((2,3),[1,2,3])#(shape,items)

array([[1, 2, 3],
       [1, 2, 3]])

In [30]:
#the eye function return an identity matrix
np.eye(4)#(row=4,column=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
# the empty function Return an empty array with no initialised items
np.empty([2,2],dtype=int)#(shape,data type)

array([[4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408]])