In [1]:
import numpy as np

In [2]:
#indexing

In [3]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#we want number 5
a[4]#[number of index]

5

In [5]:
#[-1]
a[-1]#the last item

9

In [6]:
#an array of items
a[[0,4,7]]

array([1, 5, 8])

In [7]:
#two dimension array
b= np.arange(1,10).reshape((3,3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#I want number 5
b[1][1]#[row][column]

5

In [9]:
#if i want the row 0
b[0]

array([1, 2, 3])

In [10]:
#slicing

In [11]:
a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [12]:
a[1:4]

array([2, 3, 4])

In [13]:
a[1:4:3]#[start:end:gap]

array([2])

In [14]:
a[:5:2]

array([1, 3, 5])

In [15]:
a[::2]

array([1, 3, 5])

In [16]:
a[:5:]

array([1, 2, 3, 4, 5])

In [50]:
#two dimension
a = np.arange(1,10).reshape((3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1]:
a[0,:]

array([1, 2, 3])

In [19]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [20]:
a[[0,2],0:2]#[[row,row],start:end]

array([[1, 2],
       [7, 8]])

In [21]:
#iterating

In [22]:
for item in a.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [23]:
#apply_along_axis function
np.apply_along_axis(np.mean,axis=1,arr=a)#(operation,axis,array)

array([2., 5., 8.])

In [24]:
#conditions

In [25]:
a = np.random.random((4,4))

In [26]:
a

array([[0.70446185, 0.76664168, 0.32421346, 0.32200542],
       [0.84933571, 0.43937071, 0.66630673, 0.47829455],
       [0.08886052, 0.17892382, 0.53810917, 0.50173775],
       [0.26872102, 0.53710662, 0.94867333, 0.90822663]])

In [27]:
a <0.2

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True, False, False],
       [False, False, False, False]])

In [28]:
a[a<0.2]

array([0.08886052, 0.17892382])