In [1]:
import numpy as np

In [2]:
#join

In [3]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
y= np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.vstack((x,y))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.hstack((x,y))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [7]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])

In [8]:
np.column_stack((x,y,z))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
np.row_stack((x,y,z))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#split

In [11]:
a = np.arange(16).reshape((4,4))

In [12]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
[b,c] = np.hsplit(a,2)#(array,number of array)

In [14]:
b

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [15]:
c

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [16]:
[b,c] = np.vsplit(a,2)#(array,number of array)

In [17]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
c

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
[x,y,z] = np.split(a,[1,3],axis=1)#(array,indexing,axis)

In [20]:
x#0 to 1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [21]:
y#1 to 3

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [22]:
z#3 to end

array([[ 3],
       [ 7],
       [11],
       [15]])

In [23]:
[x,y,z] = np.split(a,[1,3],axis=0)#(array,indexing,axis)

In [24]:
x#0 to 1

array([[0, 1, 2, 3]])

In [25]:
y#1 to 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
z#3 to end

array([[12, 13, 14, 15]])

In [27]:
#views and copies

In [28]:
a = np.array([1,2,3,4])
b=a

In [29]:
a

array([1, 2, 3, 4])

In [30]:
b

array([1, 2, 3, 4])

In [31]:
a[0] = 100

In [33]:
print(a)
print(b)
#they are views for each others

[100   2   3   4]
[100   2   3   4]


In [34]:
a = np.array([1,2,3,4])
b = a.copy()

In [35]:
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [36]:
a[0] = 100

In [37]:
print(a)
print(b)
#b copies from a

[100   2   3   4]
[1 2 3 4]
