In [1]:
import numpy as np

In [2]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
#the reshape function
a.reshape(3,4)#(row,column)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
#another way
a.shape = (3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
#Convert two dimension array to One dimension
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
a.shape = (3,4)
a
#the transpose function that Convert row to column and column to row
a.transpose()#shape(4,3)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [7]:
#mathematical Operations

In [8]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [9]:
#the + symbol
a+4

array([4, 5, 6, 7, 8])

In [10]:
b= np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [11]:
a+b

array([ 5,  7,  9, 11, 13])

In [12]:
np.add(a,b)

array([ 5,  7,  9, 11, 13])

In [13]:
# the - symbol
a-4

array([-4, -3, -2, -1,  0])

In [14]:
a-b

array([-5, -5, -5, -5, -5])

In [15]:
np.subtract(a,b)

array([-5, -5, -5, -5, -5])

In [16]:
#the * symbol
a *2

array([0, 2, 4, 6, 8])

In [17]:
a*b

array([ 0,  6, 14, 24, 36])

In [18]:
np.multiply(a,b)

array([ 0,  6, 14, 24, 36])

In [20]:
#the / symbol
a /2

array([0. , 0.5, 1. , 1.5, 2. ])

In [21]:
a /b

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [22]:
np.divide(a,b)

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [24]:
#Matrix multiplication

In [26]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
a.shape

(2, 3)

In [27]:
b = np.array([7,8,9])
b.shape

(3,)

In [28]:
#the dot Function that return an array of the a*b
c = np.dot(a,b)
c

array([ 50, 122])

In [29]:
c.shape

(2,)

In [30]:
#the decrement and increment Operations

In [31]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [32]:
a +=1

In [33]:
a

array([1, 2, 3, 4])

In [34]:
a+=5
a

array([6, 7, 8, 9])

In [35]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [36]:
a -=1

In [37]:
a

array([-1,  0,  1,  2])

In [38]:
a -=5

In [40]:
a

array([-6, -5, -4, -3])

In [41]:
#the universal functions

In [42]:
a = np.arange(1,11)

In [43]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [45]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [46]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [47]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [48]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [52]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [53]:
#the aggregate functions

In [54]:
a = np.array([3.3,4.5,1.2,5.7,0.3])
a

array([3.3, 4.5, 1.2, 5.7, 0.3])

In [55]:
a.sum()

15.0

In [56]:
a.max()

5.7

In [57]:
a.min()

0.3

In [58]:
a.argmax()#return the index of max

3

In [59]:
a.mean()#avg

3.0

In [60]:
a.std()#Standard deviation

2.0079840636817816